// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfI4Iaz8dp9g96UE0MbYKjQH71LmbzuOg',
    appId: '1:546287465837:web:6cf28af6df5a62aef61664',
    messagingSenderId: '546287465837',
    projectId: 'polin-a2082',
    authDomain: 'polin-a2082.firebaseapp.com',
    storageBucket: 'polin-a2082.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2M_3Xj3lyhLWkJRGyOithklaBXGtIA1A',
    appId: '1:546287465837:android:7ee2af64801fe26af61664',
    messagingSenderId: '546287465837',
    projectId: 'polin-a2082',
    storageBucket: 'polin-a2082.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaqP052tNzLmdtJk9DCNVEfScEd7y1UT4',
    appId: '1:546287465837:ios:e54957a4e14e7055f61664',
    messagingSenderId: '546287465837',
    projectId: 'polin-a2082',
    storageBucket: 'polin-a2082.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaqP052tNzLmdtJk9DCNVEfScEd7y1UT4',
    appId: '1:546287465837:ios:e54957a4e14e7055f61664',
    messagingSenderId: '546287465837',
    projectId: 'polin-a2082',
    storageBucket: 'polin-a2082.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfI4Iaz8dp9g96UE0MbYKjQH71LmbzuOg',
    appId: '1:546287465837:web:d79f64803cffcca8f61664',
    messagingSenderId: '546287465837',
    projectId: 'polin-a2082',
    authDomain: 'polin-a2082.firebaseapp.com',
    storageBucket: 'polin-a2082.appspot.com',
  );
}
